### PR TITLE
Change scooter icon

### PR DESCRIPTION
**Pull request by Beck-berry**
## Proposed Changes
Based on #762 
 
image

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

### CODE REVIEW

**Comment by hbruch** [comment]
Could you please use the red-orange circle scooter in the popup as well? And could you use consistent font style for the popup, as currently, we seem to apply two different styles for transit stops and other popups.

**Comment by hbruch** [comment]
And please change the heading "Haltestelle auswählen" to "Option auswählen" (like we used in DT-1)

**Comment by Beck-berry** [comment]
>Could you please use the red-orange circle scooter in the popup as well? 

Of course, okay!

>And could you use consistent font style for the popup, as currently, we seem to apply two different styles for transit stops and other popups.
> And please change the heading "Haltestelle auswählen" to "Option auswählen" (like we used in DT-1)

If I'm correct, these will be handled by #763

**Comment by Beck-berry** [comment]
image

And since the popup and the sidebar menu uses the same image, it changed too:

image

**Review by hbruch — APPROVED** [review]
LGTM, thanks

**Pull request merged**
