### PR TITLE
Adapt walking speed options and wording

### LINKED ISSUE #625: Change the wording of the walking speeds in the german itinerary settings
The different walking speeds have bad wording in german and currently have five speeds.
image
image

Please change this for it to only propose 3 options with the following names:

English / German

Slow 2,5 km/h  /  Am wenigsten 2,5 km/h    ->   Slow 3 km/h  /  Langsam 3 km/h
Average 4,3 km/h  /  Standard 4,3 km/h    ->   Normal 5 km/h  /  Normal 5 km/h
Fast 8 km/h  /  Am meisten 8 km/h    ->   Fast 7 km/h  /  Schnell 7 km/h

(This means you can delete the "Calm / Weniger" & "Prompt / Mehr" options)

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #625

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
Screenshot 2021-06-15 at 09 51 28
Screenshot 2021-06-15 at 09 51 43

**Comment by leonardehrenfried** [comment]
Can you fix the tests?

**Comment by patrickbeck1337** [comment]
Fixed

**Comment by leonardehrenfried** [comment]
Thanks!

**Pull request merged**
