### PR TITLE
Comment out highlight circle 

### LINKED ISSUE #419: UI: Layout issue when choosing a Sharing-Angebot
Scenario:
- Choose to show "Sharing-Angebote" on the map
- Click on the Sharing-Angebot spot on the map to see its details
- The system shows an unaligned black circle around the location
image
image
image

And sometimes when you click on another Sharing-Angebot, the black circle does not disappear from the previous spot you clicked and does not appear around the one you just chose:
image

QA version:
image: mfdz/opentripplanner:otp2-3bcf0f41606d3b70f681b2f355064f71d3ace246
image: stadtnavi/digitransit-ui:fa8193fbace646e9f94132cda0732a9d8435c802
image: stadtnavi/hsl-map-server:a563129166683c99bfdedb88f00bb9117afff726
image: stadtnavi/fares-service:a9d1987be58d86b877699ede204ad537afd0bda1

### PR DESCRIPTION
**Pull request by jpidelatorre**
As discussed with @Denis306, I disabled the function that draws the highlight circle.

closes #419

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Would it not make more sense to just comment out the function calls?

**Comment by jpidelatorre** [comment]
That's what I did at first, but the linter went crazy. It doesn't like functions that are not called.

Also, it's probably a good idea to have the change in a single place.

**Comment by leonardehrenfried** [comment]
Can't you add one of those magic comments that disable the linter?

**Comment by jpidelatorre** [comment]
Done. ^^

**Pull request merged**
