### PR TITLE
Next 348 adapt display of opening hours

### LINKED ISSUE #348: Refine display of opening hours
Map feature details (e.g. parking opening hours) are currently displayed in a very verbose style. This should be replaced by a more user friendly rendering. Open hours, for example, could be displayed only for the current day, other days made visible by a click to unfold.

image
image
image

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #348

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
Change it accordingly to google maps.
image
image

**Comment by leonardehrenfried** [comment]
Would it be possible to display the current day's opening hours?

Also there is a merge conflict.

**Comment by patrickbeck1337** [comment]
> Would it be possible to display the current day's opening hours?
> 
> Also there is a merge conflict.

Added a highlighting:

image


Resolved the merge conflict.

**Comment by leonardehrenfried** [comment]
I'm sorry for not being clearer but I meant to show the current day's opening hours even in the default state. Just like Google Maps does it:

Screenshot from 2021-06-03 09-04-00

**Comment by patrickbeck1337** [comment]
Done:

image
image

**Pull request merged**
