### PR TITLE
Next 358 add more details to e charging stations

### LINKED ISSUE #353: More detailed eCharging Station info
Stadtnavi has added a layer to display charging stations for cars and bicycles.

image1

- stadtnavi should display detail information like e.g. 
- payment types
- charging speeds
- plug types

Basic information like e.g. occupancy status, plug type and details URL, symbols of plug types in SVG format as well as an endpoint to request an OCHP json response for an individual station will be provided as VectorTiles by another working package.

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #353

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
Add first details as draft. We need to discuss what we should display here. I just added something to show that it is working. 

But I think we can also do that in the follow up ticket https://github.com/stadtnavi/digitransit-ui/issues/456

image

**Comment by leonardehrenfried** [comment]
Ok, this feature has become more important and we want to tackle it this week.
@patrickbeck1337 Can you please resolve the merge conflicts so I can merge?

**Comment by leonardehrenfried** [comment]
Ah, sorry Patrick, I should have told you: since this feature's priority has increased, I decided to do the merge myself.

**Comment by patrickbeck1337** [comment]
I just saw that xD

**Pull request merged**
