### PR TITLE
Adding availability badge to charging stations

### LINKED ISSUE #613: Live status of charging stations
The charging stations should also have an availability indicator like for example the parking garages.
image

This is the only chariging station in Herrenberg that can have a live status indicator right now as it is the only one sending "availavility" data:
https://herrenberg.beta.stadtnavi.eu/ladestationen?lat=48.599106021717546&lng=8.870450779795647&name=Parkplatz+Benzstra%C3%9Fe&stationId=2950&capacity=2&available=2

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #613

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
I applied following rule:

- If the availability is 0 the red badge is shown
- If the availability is 1 the orange badge is shown
- If the availability is more than 1 the green icon is shown

Be aware that this means for Herrenberg most of the stations have the red badge. 

Unfortunately accessing the `UNKOWN` status @the-infinity mentioned in #613 is not possible when drawing the map. 
Since we are using the [tiles endpoint](https://ochp.next-site.de/tiles/16/34432/22590.mvt). Which does only return the total capacity and the available slots which is for Herrenberg most of the time 0. 

Screenshot 2021-06-15 at 09 21 53
Screenshot 2021-06-15 at 09 22 12

**Comment by hbruch** [comment]
If we have no availability realtime information, we shouldn't display any badge. If this is not in the tiles yet, the tiles need to be adapted.

**Comment by patrickbeck1337** [comment]
> If we have no availability realtime information, we shouldn't display any badge. If this is not in the tiles yet, the tiles need to be adapted.

Yes I agree. We need a flag for that in the tiles endpoint.

**Comment by the-infinity** [comment]
I could give you the attribute "cu" for "count unknown" if this helps? Then you could check if count == count unknown, and if true disabling the output.

**Comment by patrickbeck1337** [comment]
Yes that would be enough! If we agree on `cu` as `boolean` I will implement it within this PR.

**Comment by the-infinity** [comment]
cu would be integer and would count the number of unknown chargestations at this location. just a bool flag would not be so nice because at other places it may happen that just some of the stations are unknown. but for herrenberg it's almost the same: if cu > 0 then no icon.

**Comment by patrickbeck1337** [comment]
Ok fine for me

**Comment by patrickbeck1337** [comment]
@hbruch I updated the PR [accordingly](https://github.com/stadtnavi/digitransit-ui/pull/633/commits/72a8b8ae4cfeef78fd4d19d7414cc086d0e04209).

**Comment by the-infinity** [comment]
Should get outputted in tiles now

**Comment by leonardehrenfried** [comment]
Ok, not sure if this is ready for merging. If it is, @patrickbeck1337, then remove the draft and I will merge.

**Comment by leonardehrenfried** [comment]
Could you also fix what Ansgar has reported? https://github.com/stadtnavi/digitransit-ui/issues/638

Screenshot from 2021-06-16 12-34-26

**Comment by patrickbeck1337** [comment]
> Could you also fix what Ansgar has reported? #638
> 
> Screenshot from 2021-06-16 12-34-26

I think you already added something regarding this one. I also did in #632.

**Comment by patrickbeck1337** [comment]
Everything looks good from my point of view. The logic is working as expected:

Case more than 1 chargers are available:
Screenshot 2021-06-18 at 08 50 24
Case status unknown and only 1 is available (see Benzstraße):
Screenshot 2021-06-18 at 08 50 47

**Comment by leonardehrenfried** [comment]
Looking good, thanks!

**Pull request merged**
