### PR TITLE
Next 579 cargo bike booking feature

### LINKED ISSUE #579: Apply new UI to Cargo bike booking Feature
We want to implement the cargo bike booking pretty similar to the eCharging Stations.
image

The Icons used in the Design proposal are just dummy icons. We are waiting for the icons that will be provided by the city of Herrenberg. 

These are the Cargo Bike Icons that need to be used:
[lastenrad_sharing.zip](https://github.com/stadtnavi/digitransit-ui/files/6618431/lastenrad_sharing.zip)

All the other information is here: https://github.com/stadtnavi/digitransit-ui/issues/351

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #579

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
Adapted the design according to the information which is yet provided.
Be ware following information is currently not provided by the backend:
- Payment types
- Phone number

The design is not implemented 100% according to the design. This would need to rewrite HSL components like e.g. the back button or adding  new UI components like icon buttons. 

First throw looks like this:
Screenshot 2021-06-14 at 21 16 22


However it is only working for the station http://localhost:8080/fahrradstationen/cargo-bike-station going against the dev backend. 
For other stations I get http 404 errors. 
E.g.:
Screenshot 2021-06-14 at 21 08 01
@leonardehrenfried  is this intended?


I also adapted the design of the charging station sidebar content:
Screenshot 2021-06-14 at 21 04 06

**Comment by leonardehrenfried** [comment]
Since cargo bikes are now permanently enabled I removed the configuration.

**Review by leonardehrenfried — CHANGES_REQUESTED** [review]
Looks good but i think the "route from here"/"route to here" don't work, right?

**Comment by leonardehrenfried** [comment]
And yes, only the one cargo bike has a separate booking page. The rest doesn't.

Can you please only display the UI for that single cargo bike?

**Comment by leonardehrenfried** [comment]
Also, we changed the feeds so the ID of the cargo bike, that has a separate booking UI, has changed: https://dev.stadtnavi.eu/fahrradstationen/cargobike-herrenberg

**Comment by patrickbeck1337** [comment]
> And yes, only the one cargo bike has a separate booking page. The rest doesn't.
> 
> Can you please only display the UI for that single cargo bike?

So you mean only this one should have the new UI?
https://dev.stadtnavi.eu/fahrradstationen/cargobike-herrenberg


Problem: 

The API doesn't return anything right now for the existing Cargo Bike stations in herrenberg
=> https://backend.openbikebox.next-site.de/api/v1/location?slug=cargobike-herrenberg&format=object

**Comment by patrickbeck1337** [comment]
I changed the api to the production one: https://backend.open-booking.eu/api/v1/location?slug=cargobike-herrenberg

Also I only enabled the new UI for http://localhost:8080/fahrradstationen/cargobike-herrenberg
Screenshot 2021-06-18 at 09 27 08

For the other stations like `fare` or `alf` the old UI sidebar is shown:
Screenshot 2021-06-18 at 09 27 33


Route from here/ there feature is working for me:
Screenshot 2021-06-18 at 09 31 27

**Pull request merged**
