### PR TITLE
Refactor MessageBarMessage.js logic to be able to handle multiple con…

### LINKED ISSUE #607: Put information about the Beta Apps in the Static Message
The static message being displayed in the web app is currently missing information about the beta apps. 
image

- [x] Please implement the following information to that static message in a new line:
„stadtnavi gibt es demnächst auch als native App für Ihr Mobiltelefon. Testen Sie bereits heute die iOS oder Android Beta-Version der App und teilen Sie uns Ihr Feedback mit.“

- [x] Make the "iOS" and "Android" words an hyperlink with the corresponding beta invitation links:
iOS: https://testflight.apple.com/join/QaC8z0fo
Android: https://play.google.com/apps/testing/com.test.stadtnaviApp

### PR DESCRIPTION
**Pull request by patrickbeck1337**
…tent objects for static messages.

## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #607

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
Done.

Screenshot 2021-06-12 at 22 53 33

Screenshot 2021-06-12 at 22 53 42

**Comment by leonardehrenfried** [comment]
I would like to merge this but there are test failures.

**Comment by leonardehrenfried** [comment]
Sadly the test still fails.

**Comment by patrickbeck1337** [comment]
> Sadly the test still fails.

fixed

**Pull request merged**
