### PR TITLE
Adds Bike rental warning to bike itinerary

### LINKED ISSUE #465: Adjust UI to display bike rental warnings
115232399-ee0b4300-a116-11eb-9df2-7ae0198b2e41

OTP1 has a feature to allow you to drop a bike anywhere even when you're supposed to bring it back to a station. The UI should display a warning though (see above screenshots).

We added the feature to OTP2 but the API response looks a little different and needs to be added to the GraphQL query.

## Acceptance criteria
- Plan a route from Nufringen to Kuppingen
- Enable bike sharing, disable bus
- See that no warning is displayed in the UI
- Modify GraphQL query to return the property and adjust UI

@flaktack Can you please describe how to modify the graphql query to get the results?

### PR DESCRIPTION
**Pull request by andreashelms**
## Proposed Changes

  - Adds Bike rental warning to bike itinerary

image

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #465

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Thanks for this - good work!

Is it possible that the arrow has been slightly moved?

**Comment by hbruch** [comment]
Could you fix the spelling error "Leirad" in the translation to "Leihrad"

**Comment by andreashelms** [comment]
> Thanks for this - good work!
> 
> Is it possible that the arrow has been slightly moved?

Actually I didn't change that. But I now wrapped a div around the warning text and it fits better.

**Comment by leonardehrenfried** [comment]
Did you have problems finding bike rental routes, @andreashelms? I'm working on fixing this.

**Pull request merged**
