### PR TITLE
Fix sharing marker alignment when selected

### PR DESCRIPTION
**Pull request by jpidelatorre**
## Proposed Changes

  - Realigned coordinates for highlighting circles around icons.
  - Null check to avoid breakings.

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

Closes: #419

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Can you please post a screenshot and link the ticket?

**Comment by leonardehrenfried** [comment]
@jpidelatorre By the way, changed the server so that the icons should not be clipped on a tile border anymore. If you're still having problems with that, let me know.

**Comment by jpidelatorre** [comment]
> @jpidelatorre By the way, changed the server so that the icons should not be clipped on a tile border anymore. If you're still having problems with that, let me know.

@leonardehrenfried Everything was working fine before the merge with HSL (d9687f0c6). Now, icons are not being rendered when the user selects any shared service. You can see this by going to http://localhost:8080/fahrradstationen/7bd6d9cb-509b-4378-83db-cebb44ee1f6f 

This is how it looks after d9687f0c6:
image


This is how it looked like with the commit just before that one (f23e8caf6):
image

**Comment by jpidelatorre** [comment]
Here's what I did in the last commit:
- Highlighting circle now fully encloses the icon unless there's an availability badge being rendered.
- Now, availability badges only accept numbers and numbers over 9 are shown as **9+**.
- Badges are shown if there are available rides. This failed before because of an unset property.

**Comment by leonardehrenfried** [comment]
@jpidelatorre As agreed in the dev meeting today, please make an upstream ticket describing the problem of the disappearing icons when selecting a rental bike/car.

**Comment by leonardehrenfried** [comment]
@jpidelatorre Can you please link to the ticket for the missing icons?

**Comment by leonardehrenfried** [comment]
@jpidelatorre You told me in Zulip that you cannot reproduce the missing icon upstream but I can: https://reittiopas.hsl.fi/pyoraasemat/215

For me it looks like this:

Screenshot from 2021-05-19 10-08-34

Can you reproduce this?

**Comment by leonardehrenfried** [comment]
Aha, it's a Firefox problem. In Chrome it looks like this:

Screenshot from 2021-05-19 10-11-56

**Comment by jpidelatorre** [comment]
@leonardehrenfried  #472 refers to the problem of the icons disappearing. Can we fix it there?

**Comment by leonardehrenfried** [comment]
@jpidelatorre I'm going to close this. Now that Patrick has fixed the display of the icons, can you take the latest `next` branch and port you changes again onto a new branch?

**Comment by jpidelatorre** [comment]
> @jpidelatorre I'm going to close this. Now that Patrick has fixed the display of the icons, can you take the latest `next` branch and port you changes again onto a new branch?

Sure, I will.

**Comment by jpidelatorre** [comment]
@leonardehrenfried This PR has diverged too much since it was branched before the upstream merge. Instead of trying to rewrite history and fix the branch, I branched `next` and applied only the required changes. The new PR is #498 .

**Pull request closed without merging**
