### PR TITLE
Next 500 add details information for e charging pop up

### LINKED ISSUE #500: Add detail informations to eCharging pop up
As we agreed in todays web dev meeting we first will add all the new detail informations to the pop up. And as follow up apply the new UI design as side panel in #456 

The pop up should include following information:

- Name of the station
- Opening time
- Connector max amperage and power type
- Number of free slots
- Number of total slots
- Accepted payment types
- Address 
- Phone number
- Deep link to https://direct.emobilitycloud.com for each station

Design as reference:
image

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #500

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
First throw. Icon color is still wrong. For some reason it is not taken. But I didn't find the cause yet.

image
image

**Comment by hbruch** [comment]
As we are in the EU, could you please replace the currency symbol $ with something more appropriate, e.g. €?

**Comment by hbruch** [comment]
Is the address returned as displayed? Usually, we don't separate postal code and city by colon

**Comment by the-infinity** [comment]
This looks fine :) @hbruch already mentioned some points, a few further comments:

1) yes, the address comes from OCPI
2) Type F is the international standard nobody knows here, it's called "SchuKo" in common tongue
3) If there's the attribute REMOTE_START_STOP_CAPABLE, you can add the payment method "App"
4) It would be an good idea to mark the blocked chargestations. Especially when it comes to different charging speeds (like fast and normal charging at one location), it makes quite a difference which plug is blocked
5) if you want to make companies very happy you can plan to integrate the logos of the operator. If we want to do this, we should ask Dreso to collect the Logos for the stations in Herrenberg
6) it's also an idea to show the parking_restrictions, like "electric cars only". This would also be something which has to be asked because it's in no public database

**Pull request merged**
