### PR TITLE
Use triangle factors when bike is enabled

### LINKED ISSUE #313: Re-add triangle safety factors for cycling
DT allowed you to customize the so-called triangle factors for cycling where you could give priorities for distance, safety and slope.

It's gone in DTnext, so lets bring it back, as we've spent quite a bit of time tuning this.

Acceptance criteria:

- Find relevant GraphQL queries in `SummaryPage`
- Set `optimizeType=TRIANGLE`
- Allow configuration of the query variables `safetyFactor`, `speedFactor` and `slopeFactor`

### PR DESCRIPTION
**Pull request by Beck-berry**
## Proposed Changes
  - Added the triangle factors to the hbnext config.
  - Get triangle factors from the graphQL query.
  - Use these only when bike is also enabled, otherwise optimize type is QUICK.

## Review
  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #313

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
This appears to break the "Later" and  "Earlier" trip search. Can you check it out?

**Comment by leonardehrenfried** [comment]
After quick analysis I can see that he triangle factors are missing from the earlier/later queries.

**Comment by Beck-berry** [comment]
Sorry, fixed! :rocket:

**Comment by leonardehrenfried** [comment]
Thanks it's a big pain to have so many queries! Who is supposed to keep all of them in his head!?

**Pull request merged**
