### PR TITLE
Fix/373

### LINKED ISSUE #373: Prettify popups (again)
Since I merged with upstream again many popups look broken. Presumably this is because some CSS changed upstream.

## Cycle infrastructure

Screenshot from 2021-04-28 13-14-57
Screenshot from 2021-04-28 13-14-31

## Car parks

Not quite as bad.

Screenshot from 2021-04-28 17-20-56
Screenshot from 2021-04-28 17-20-26

## Public toilets

Screenshot from 2021-04-28 17-24-19

## Weather stations

Screenshot from 2021-04-29 14-53-10

### PR DESCRIPTION
**Pull request by aaronyamil**
## Proposed Changes

  - fix about this ticket https://github.com/stadtnavi/digitransit-ui/issues/373

## Review

  - Read and verify the code changes
  - the popup on the map has a correct style.

closes #373

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Ok, I think I wasn't clear what I meant with "prettify": I wanted the popups to look nice in the new style rather than reverting to the old button style.

What this means is to adjust the padding/margin so that the text has the same distance to the edge on all sides.

The button style can stay is it is currently.

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried I am reviewing my code for this pull request and the following is the result:
image
Car Parks
image
Public toilets
image

I think the fix is done. The margins and button are good.

**Comment by leonardehrenfried** [comment]
Thanks but can you restore the DT2 button style?

Screenshot from 2021-05-04 10-10-00

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried the pull request is updated. Please needs your check
image
The DT2 button style is back.

**Comment by leonardehrenfried** [comment]
This commit contains a large number of commits unrelated to the actual change. Can you fix that? You probably need to rebase.

**Pull request closed without merging**
