### PR TITLE
Fix: Update small dot  marker colors

### LINKED ISSUE #398: Symbol colors don't match stadtnavi colors
When zoomed out, bus stop/train/tram station icon colors don't match stadtnavi's icons colors:

grafik

Expected colors as in DT-1 (herrenberg.stadtnavi.de):
grafik

### PR DESCRIPTION
**Pull request by andreashelms**
- Fixed missing dot marker colors

image

closes #398

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
Train station still have the wrong color.

image

image

**Comment by andreashelms** [comment]
> Train stations still have the wrong color.
> 
> image
> 
> image

@patrickbeck1337 Should have correct color now.

**Comment by andreashelms** [comment]
image


@patrickbeck1337 Should have correct color now.

**Comment by patrickbeck1337** [comment]
closes #398

**Pull request merged**
