### PR TITLE
Add bike rental alerts

### LINKED ISSUE #307: Re-add bike sharing alert about free floating drop off
The following UI is missing:

Screenshot from 2020-11-20 12-07-00

### PR DESCRIPTION
**Pull request by Beck-berry**
## Proposed Changes
Added bike sharing alert message:
image

## Review
  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #307

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Screenshot from 2020-11-20 13-33-26

I'm seeing the alertId in the JSON response. Perhaps there is another on of those query blocks where you need to add it.

**Comment by leonardehrenfried** [comment]
Screenshot from 2020-11-20 17-33-30

I added the missing piece to the query. @Beck-berry can you adjust the styling?

**Comment by Beck-berry** [comment]
Yes, thank you! Will be done on Monday!

**Comment by leonardehrenfried** [comment]
Can you rebase onto master? There are merge conflicts.

**Comment by leonardehrenfried** [comment]
Please also add the button to book the shared bike.

**Comment by leonardehrenfried** [comment]
And can you add a little more padding to the box so that it looks more like the old one?

Screenshot from 2020-11-23 11-56-34

**Comment by Beck-berry** [comment]
image

**Pull request merged**
