### PR TITLE
Merge upstream/next

### PR DESCRIPTION
**Pull request by Beck-berry**
## Proposed Changes
  - Merged components, package.json and yarn.lock.
  - Added German translation for the new texts.

Functionality is not yet properly tested!

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
There seem to be failing unit test.

Also, could you deactivate the e2e test jobs for Github Actions?

**Comment by Beck-berry** [comment]
- [x] don‘t get parkings popup 
- [x] cannot switch off subway and train in the map selector.
- [ ] failing unit tests
- [x] deactivate the e2e test jobs (@leonardehrenfried did you do this already?)

**Comment by leonardehrenfried** [comment]
Yes, I did. And I fixed the popup.

**Comment by Beck-berry** [comment]
There is still a fail (actually two, but they are the same kind and I think that they need the same fix) which I could not resolve yet. The other tests and wrongly merged files got their fixes.

**Comment by leonardehrenfried** [comment]
I've fixed the tests.

**Pull request merged**
