### PR TITLE
Next 368 add weather station map layer

### LINKED ISSUE #368: Add weather stations map layer
We added a weather station map layer to DT1.

Screenshot from 2021-04-20 17-23-45

Original PR: https://github.com/stadtnavi/digitransit-ui/pull/334/

Please port the feature to DT next.

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #368

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
@leonardehrenfried I tried to just copy the existing code from DT1 (master) without changing a lot. However the logo changed due some changes from HSL. I tried to orientate on the changes you did within the dynamic parking lots map layer. 

But still the pop up looks different and the logo as well. Compared to DT1.

image

Do you have an idea what I am missing here?

**Comment by leonardehrenfried** [comment]
Thanks for the PR.

We did a refactoring of the messy DT1 TileLayerContainer a while ago (https://github.com/HSLdevcom/digitransit-ui/pull/3244) but sadly this was not applied to DTnext. So now you're applying code from the refactored version to the un-refactored version. No wonder this is confusing and frustrating.

On top of this the CSS for the popup has recently changed upstream and this made all of our popups look ugly. We're tracking this here: https://github.com/stadtnavi/digitransit-ui/issues/373

I don't think we need to tackle _this_ problem in this PR here but in a separate one.

Regarding the icon: it appears that I changed it after the initial PR. Here is the commit: https://github.com/stadtnavi/digitransit-ui/commit/a542e9df4edb01a41075af851e8369b1cf1d8c44#diff-a6d1feeee2fcb53de8eda741cdc8100f80ae0d4188a42ecda1be4e14a92b0c17

I did the following:

- I fixed the way that properties are passed down
- I merged `next` to fix the layer URLs

The popup now looks like this:

Screenshot from 2021-04-29 14-50-02

Can you do the following please?

- Use the icon from the above commit
- fix the display of the translations and the "updated at"

**Comment by patrickbeck1337** [comment]
@leonardehrenfried  I updated the PR. Added your requested changes. The card header structure and styling changed a bit in the next branch. Should we keep it or overwrite the the styling?

image

**Comment by hbruch** [comment]
In the screenshot there is a mix between English and German. Could you please fix this?

**Comment by leonardehrenfried** [comment]
Since we want to get rid of the popups eventually anyway, please don't spend too much time on, however please fix the large margin between "Road weather" and "Schiesstaele".

**Comment by patrickbeck1337** [comment]
> In the screenshot there is a mix between English and German. Could you please fix this?

Good hint i forgot to migrate those translation keys. Also overwrote the styling for the .card-sub-header

image


image

**Comment by leonardehrenfried** [comment]
This looks really good - thanks. 

I noticed that I tweaked this map layer after the initial pull request. 

https://github.com/stadtnavi/digitransit-ui/commits/master/app/component/WeatherStationContent.js

Can you copy over the latest version of `WeatherStationContent,js` from the master branch, so that we have all the latest changes?

**Comment by leonardehrenfried** [comment]
Screenshot from 2021-04-30 15-47-56

Aaron has been working on the map layer switcher. Can you adjust the weather stations one as well, please?

**Comment by leonardehrenfried** [comment]
And the map layer switcher needs a translation.

**Comment by patrickbeck1337** [comment]
> Screenshot from 2021-04-30 15-47-56
> 
> Aaron has been working on the map layer switcher. Can you adjust the weather stations one as well, please?

Good point done

**Comment by leonardehrenfried** [comment]
> This looks really good - thanks.
> 
> I noticed that I tweaked this map layer after the initial pull request.
> 
> https://github.com/stadtnavi/digitransit-ui/commits/master/app/component/WeatherStationContent.js
> 
> Can you copy over the latest version of `WeatherStationContent,js` from the master branch, so that we have all the latest changes?

If my request wasn't clear, please have a look at https://github.com/stadtnavi/digitransit-ui/pull/375/commits/ae4f9203e0c8ac8545917e0e1fa5b4577f24a501 where I ported over the changes from the current master.

Merging this now.

**Pull request merged**
