### PR TITLE
Move charging stations popup content to sidebar

### PR DESCRIPTION
**Pull request by andreashelms**
## Proposed Changes

  - Move charging stations popup content to sidebar

image
image

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

for #344

### CODE REVIEW

**Comment by andreashelms** [comment]
This was the popup before:
image

Where should the buttons on the bottom appear? Also in the sidebar?

**Comment by leonardehrenfried** [comment]
Looks good!

Lets move the buttons into the panel and let people look at a it. If they think it should be removed, we will remove it again.

**Comment by leonardehrenfried** [comment]
Is this ready for merging?

**Comment by andreashelms** [comment]
> Is this ready for merging?

Nope, still working on that one. Will be ready soon.

**Comment by leonardehrenfried** [comment]
:+1:

**Comment by andreashelms** [comment]
> 👍

@leonardehrenfried done

**Pull request merged**
