### PR TITLE
Add rail subicon to park-and-ride in custom settings panel

### LINKED ISSUE #640: Change P&R Symbol in the Itinerary Settings
The itinerary settings are currently using the car icon for the "Park-and-Ride" setting.
image

Please replace this Icon in the settings by this Icon: 
[car-train-1.zip](https://github.com/stadtnavi/digitransit-ui/files/6658318/car-train-1.zip)
image

### PR DESCRIPTION
**Pull request by Beck-berry**
## Proposed Changes
image

## Review
  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #640

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Did you notice that the original PR contained a zipped SVG? https://github.com/stadtnavi/digitransit-ui/files/6658318/car-train-1.zip

That what you only have to exchange the SVG and don't have to touch JS or SVG.

**Comment by Beck-berry** [comment]
Oh, I can make it that way, of course. Sorry if I made it too complicated.

**Comment by MartinH-open** [comment]
> That what you only have to exchange the SVG and don't have to touch JS or SVG.
That is why daily Stand-Ups are so important ..  ;)

---
BTW - new nice icon is fine.
But - from user perspective - it is unclear why to use this Park&Ride option instead of just enable Car and Train/S-Bahn/Bus .. ?
Should selecting Car and Train give me the same option as Park&Ride?
If not please explain in the UI when to use Park&Ride and when use Car only.  (Think from user perspective)
In web UI a mouse-over text could explain what to option allows what.
In then app UI perhaps add a "?" symbol to pop up the explanation text or touch and hold the Park&Ride text to display a pop up.

**Comment by Beck-berry** [comment]
With the original SVG icon it looks like:
image

**Comment by leonardehrenfried** [comment]
I've added compilation step for the icons: https://github.com/stadtnavi/digitransit-ui/blob/next/docs/Icons.md

Can you follow these instructions?

**Comment by Beck-berry** [comment]
Okay, I wasn't aware of this, thanks for the info!
I committed both files, is it right?

**Comment by leonardehrenfried** [comment]
But there seems to be a merge conflict. Is the script perhaps ordering the icons differently on your machine? Can you delete it and recompile?

**Comment by leonardehrenfried** [comment]
Or try rebasing/

**Comment by leonardehrenfried** [comment]
Looks much better.

**Pull request merged**
