### PR TITLE
updated 'Nette Toilette' layer

### LINKED ISSUE #258: Recreate Nette Toilette GeoJSON layers
There have been some small changes in the OSM data of Nette Toilette.

Please regenerate the GeoJSON layer.

### PR DESCRIPTION
**Pull request by meromisi**
## Proposed Changes

  - regenerated `Nette Toilette` layer

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #258

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Looks good.

However, I forgot to tag one place correctly: https://www.openstreetmap.org/node/2406796591

They definitely are part of Nette Toilette so please change the tags accordingly.

- it has a changing table
- is wheelchair accessible

**Comment by meromisi** [comment]
I added the new node, it wasn't part of a building so I treated it as a unique node. I hope it's fine you can check it out at the same link [here](https://www.openstreetmap.org/node/2406796591). I also modified the python script too because it sets the name to `name + "Toilette"` and in this case it would be `Toilet "Toilet"` so for separate nodes now it only says `Toilet` or `Nette Toilette`.

**Comment by leonardehrenfried** [comment]
Good work, but can you check the id of the node `2406796591` and if that matches give it the name "Waldseilgarten".

**Comment by meromisi** [comment]
image
image

**Pull request merged**
