### PR TITLE
Missing translations 386

### LINKED ISSUE #386: Missing translations
There are a couple of German translations missing

grafik

grafik

grafik

### PR DESCRIPTION
**Pull request by aaronyamil**
## Proposed Changes

  - Update the traslation file for German and English

## Review

  - Read and verify the code changes

closes #386

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
The diff is way to big to the reviewed. Can you nake it so small that I can see the differences?

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried 
We practically have a new file of translations.

The reasons are as follows:
- The translations had different formats: 'field': 'value', "field": "value", field: 'value' and vice versa.
- It was not arranged alphabetically.
- Not only 7 translations were missing. I did about 40 updates from English to German and vice versa. Now they both have the same, 644 translations.

It was very slow because I had to go one by one. Help me with a format json tool and sorter json tool, after that use a compare json tool.

I can not make the review easier. But we can have a call and I can show you how I have tested my solution.

**Comment by leonardehrenfried** [comment]
I disabled the check for the alphabetic ordering - it is no longer required.

The idea behind the original ticket was not to translate _everything_ but simply adding the we missing translation strings.

I think it would be quicker if we let someone speaking German take over this task.

**Comment by MartinH-open** [comment]
> I disabled the check for the alphabetic ordering - it is no longer required.
> 
> The idea behind the original ticket was not to translate _everything_ but simply adding the we missing translation strings.
> 
> I think it would be quicker if we let someone speaking German take over this task.

Is there some online translation tool where people could grab a few translations and propose their improved translation?
Would be great to get some context/comments for each of the strings to translate.
How to handle parameters in strings?

**Pull request closed without merging**
