### PR TITLE
Next 379 adapt sharing icons

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
While talking to @aaronyamil yesterday I remembered something that I completely forgot! Last year I wrote a little "compilation" script that combines the upstream SVGs with our downstream ones without you having to manually copy over SVGs from one file to another.

It's documented here: https://github.com/stadtnavi/digitransit-ui/blob/next/docs/Icons.md

Can you please adjust your PR so that it takes advantage of this process?

I totally apologise for not remembering earlier.

**Comment by patrickbeck1337** [comment]
Done, pls check again.

**Comment by leonardehrenfried** [comment]
Screenshot from 2021-05-05 09-18-48

I'm still seeing a size difference. Can you fix that? Maybe you just need to tweak the viewport.

**Comment by patrickbeck1337** [comment]
> Screenshot from 2021-05-05 09-18-48
> 
> I'm still seeing a size difference. Can you fix that? Maybe you just need to tweak the viewport.

I adapted the icon again. Looks good now I would say.


image

**Comment by leonardehrenfried** [comment]
Good work, thanks!

**Pull request merged**
