### PR TITLE
Adding static message. Removing json since it is not used anymore.

### LINKED ISSUE #537: Enable static messages
Digitransit-1 supported static messages displayed on startup. They can be used to display the cookie consent, imported alerts or notifications like advertisement for new stadtnavi features or mobility options. In the config, it used to be configured via `staticMessagesUrl: STATIC_MESSAGE_URL`

These should be reactivated in DT-2, example content:

```
{"staticMessages": [{
	"content": {
		"en": [
			{"content": "Public Beta", "type": "heading"},
			{"content": "This stadtnavi version currently is in public beta. You have suggestions or issues? Please give us feedback.", "type": "text"},
			],
		"de": [
			{"content": "Öffentliche Beta-Version", "type": "heading"},
			{"content": "Diese stadtnavi Version befindet sich derzeit im öffentlichen Probebetrieb. Anregungen oder Probleme? Geben Sie uns gerne Feedback.", "type": "text"},
			],
		}, 
"type": "info", 
"id": "01062021_0727", 
"persistence": "repeat", 
"icon": "info"}]
}
```

(Fot format details, a look into [MessageStore.js](https://github.com/stadtnavi/digitransit-ui/blob/next/app/store/MessageStore.js) might be helpful)

### PR DESCRIPTION
**Pull request by patrickbeck1337**
## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #537

### CODE REVIEW

**Comment by patrickbeck1337** [comment]
Fixed.
image

**Comment by hbruch** [comment]
Is staticMessageUrl not supported any longer? Instead of inlining the messages in the config, we should rather switch to an externally hosted file which can be updated (e.g. by Herrenberg) without rebuilding/deploying the application.

**Comment by MartinH-open** [comment]
> rather switch to an externally hosted file which can be updated (e.g. by Herrenberg) without rebuilding/deploying the application

I very much support this approach. Everything(!) specific to Herrenberg should be configurable in some separate config file(s). Hopefully applying config changes by "reload config" interface. Later it would be great to have some UI for (re)defining all the config parameters in an Admin/Config Interface.

**Comment by patrickbeck1337** [comment]
@hbruch good point, I reverted the change. And fixed the json structure. That was is. So we are using the staticMessagesUrl logic again.

**Pull request merged**
