### PR TITLE
Fix/378

### LINKED ISSUE #378: Fix background layer switcher
The background layer switcher looks a little broken.

Screenshot from 2021-04-29 16-41-07

Acceptance criteria
- Display dot in the radio button (maybe another icon is missing)
- Add margin to the heading
- Line up the radio buttons with the checkboxes in the section above

### PR DESCRIPTION
**Pull request by aaronyamil**
## Proposed Changes

  - fix for this ticket https://github.com/stadtnavi/digitransit-ui/issues/378

## Review

  - Read and verify the code changes
  - I fixed the radiobuttons inside the Map Background 
  - I put my fix about the scrool in the switcher map again (https://github.com/stadtnavi/digitransit-ui/issues/365)

closes #378

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Can you fix the linting errors, please?

**Comment by leonardehrenfried** [comment]
Screenshot from 2021-05-03 11-24-37

Can you make the radio buttons larger and line up the label text with the labels above?

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried I will fix the conflicts. And the  linting errors is working now.
About to make the radio buttons larger, I need to work on that. 
Thanks

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried the pull request is updated, with the last suggestion. 
The checkboxes are working well and has a new style.
image
I hope It has the expected.  The unit test is running without errors and the linters are ok.

**Comment by aaronyamil** [comment]
I created a new pull request https://github.com/stadtnavi/digitransit-ui/pull/403  more clean.

For this reason I closed this PR

**Pull request closed without merging**
